eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    lease-renewal-interval-in-seconds: 10
    non-secure-port: 80

server:
  port: ${PORT:8761}
#  error:
#    whitelabel:
#      enabled: false

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.boot: 'DEBUG'

management:
  endpoints:
    web:
      exposure:
        include: ["*"]

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NeverMore93/eureka-config-repo
          basedir: target/config
      enabled: false
