eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    lease-renewal-interval-in-seconds: 10
    non-secure-port: 80

server:
  port: 8761

logging:
  level:
    com.netflix.discovery: 'DEBUG'
    org.springframework.cloud: 'DEBUG'
    org.springframework.boot: 'DEBUG'
    org.springframework.web: 'DEBUG'

management:
  endpoints:
    web:
      exposure:
        include: ["*"]
  info:
    git:
      mode: full
  cloudfoundry:
    skip-ssl-validation: true
#  server:
#    port: 9001

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NeverMore93/eureka-config-repo
          basedir: target/config
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

ribbon:
  eager-load:
    enabled: true
